### ISSUE TITLE
Requesting Next on date when not required

### ISSUE THREAD

**Issue by portedison** [gregplaysguitar/django-next-prev#1]
With the following model setup,
``` python
date = models.DateField(db_index=True,
        default=date.today(),
        blank=True, null=True)
class Meta:
        ordering = ('sort_order', '-date', 'pk')
```
If I request `next_live()` and have not set the date I get the following error.

`ValueError: Cannot use None as a query value`

The q_list var is 
``` sql
[<Q: (AND: ('sort_order__gt', 0))>, <Q: (AND: ('date__lt', None), ('sort_order', 0))>, <Q: (AND: ('pk__gt', 2), ('date', None), ('sort_order', 0))>, <Q: (AND: ('pk', 2), ('pk__gt', 2), ('date', None), ('sort_order', 0))>]
```

**Comment by gregplaysguitar** [comment]
Hey, did you resolve this in the end? I think the problem is that you shouldn't order on a nullable field.

**Comment by portedison** [comment]
Yeah in the end I just made the field non nullable. Makes sense.

**Comment by gregplaysguitar** [comment]
Cool. It's noted in the readme now anyway
