### ISSUE TITLE
Ordering on an optional field.

### ISSUE THREAD

**Issue by portedison** [gregplaysguitar/django-next-prev#3]
If product isn't assigned a collection_group it responds, `ValueError: Cannot use None as a query value`, is it possible to skip over optional if not assigned a value? Having that ordering is quite useful in the admin view.

``` python
class Product(BaseSortedModel, ICartItem):
    collection = models.ForeignKey(Collection, on_delete=models.PROTECT,
                                   related_name='products')
    collection_group = models.ForeignKey(CollectionGroup,
                                         on_delete=models.PROTECT,
                                         related_name='products',
                                         blank=True, null=True)
    class Meta:
        ordering = ('collection', collection_group, 'sort_order', 'pk', )
```

**Comment by gregplaysguitar** [comment]
I don't think so sorry. If the value is null then there's no way to know how to order the queryset. You can add ordering specifically to the admin using ModelAdmin.get_queryset
